### ISSUE TITLE
Create a Demo Preview site

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/noto-free#1]
It could be useful for users to have a full demo preview of how Noto Free could look like, even we're not able to make it available for import (yet) due to WPorg restrictions.

Let's duplicate the main demo and install the lite version at http://demos.pixelgrade.com/noto-lite

- [x] Create the Demo Preview 
- [x] Update ```README.md```

**Comment by vladolaru** [comment]
@georgeolaru I have uploaded and activated the Free version of Noto on our demos install.

**Comment by georgeolaru** [comment]
Thanks, @vladolaru! I have updated the `readme.md` with the new links and I will close this issue now.
