### ISSUE TITLE
Profile Photo is not visible anymore

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/noto-free#26]
Even if there's an image uploaded via Customizer for the Profile Photo, the image is not displayed on site. 

![Screenshot 2021-07-14 151016](https://user-images.githubusercontent.com/6790170/125935470-d1d71799-c3a1-4588-8179-5626bbf7ce77.jpeg)

Tested locally with the latest version of Noto Free (1.2.1) and the previous version, too (1.2.0).

**Comment by alinclamba** [comment]
[+1](https://secure.helpscout.net/conversation/1590411771/58886?folderId=1142154)

**Comment by cdiegosr** [comment]
I am trying to debug this yet, no success

**Comment by alinclamba** [comment]
[+1](https://secure.helpscout.net/conversation/1595714886/59014?folderId=1083386)
