### ISSUE TITLE
my blog is not fully responsive

### ISSUE THREAD

**Issue by raresiordache** [pixelgrade/noto-free#8]
hello, 

I installed your theme on my blog, but I have an issue> my website became non-responsive on mobile. 
raresiordache.ro is my website. Google tool is saying that my blog is responsive, but, if you want to check the post content, you ll see that there are some issues. 
please, advice me to repair the website because I don t want to remove the theme, is too nice :)

thank you

**Comment by alinclamba** [comment]
**L.E.** Internal note — support ticket ID for reference — `#44199`
